name: build-docker-image-and-push-to-ecr

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required for actions/checkout

on:
  push:
    branches:
      - main
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Display workdir
        run: |
          echo ${GITHUB_WORKSPACE}
          
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
            role-to-assume: arn:aws:iam::607684260657:role/github-actions-access-role
            aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create .env and key files
        env:
          env_vars: ${{ secrets.PROD_ENV }}
          key_file: ${{ secrets.IETT_JUMPHOST_KEY }}
        run: |
          echo "$env_vars" > prod.env
          mkdir keys
          echo "$key_file" > keys/iett-jumphost-key.pem
      - name: Build, tag and push the image
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          docker_build_dir: "."
          path_to_dockerfile: "./Dockerfile"
          image_tag: "iett-website-image"
          aws_account_id: 6076-8426-0657
        run: |
          docker build "${{ inputs.docker_build_dir }}" -f "${{ inputs.path_to_dockerfile }}" -t "$IMAGE_TAG" --platform=linux/amd64
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker image ls
          docker tag "$IMAGE_TAG" "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"

